spring:
  application:
    name: blog-api
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: HR
    password: qwerqwer
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect


